<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit06ad8f382ca9f86e15ecb5a5d79ac290
{
    public static $files = array (
        '04c6c5c2f7095ccf6c481d3e53e1776f' => __DIR__ . '/..' . '/mustangostang/spyc/Spyc.php',
    );

    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DeviceDetector\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DeviceDetector\\' => 
        array (
            0 => __DIR__ . '/..' . '/matomo/device-detector',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit06ad8f382ca9f86e15ecb5a5d79ac290::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit06ad8f382ca9f86e15ecb5a5d79ac290::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit06ad8f382ca9f86e15ecb5a5d79ac290::$classMap;

        }, null, ClassLoader::class);
    }
}
